export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  VERIFY_TOKEN: 'VERIFY_TOKEN',

  ORDERS: 'ORDERS',
  PRODUCTS: 'PRODUCTS',
  CARTS: 'CARTS',
  CATEGORIES: 'CATEGORIES',
  CUSTOMERS: 'CUSTOMERS',
  TAGS: 'TAGS',
  POSTS: 'POSTS',

  PERMISSIONS: 'PERMISSIONS',
  DOMAINS: 'DOMAINS',
  ADMINS: 'ADMINS',
  BUSINESS_TYPES: 'BUSINESS_TYPES',
  USER: 'USER',
  RESOURCES: 'RESOURCES',

  THEMES: 'THEMES',
  VENDORS: 'VENDORS',
  STORES: 'STORES',

  SUBSCRIPTION_PLANS: 'SUBSCRIPTION_PLANS',
  ROLES: 'ROLES',
};
